
CREATE DATABASE MATERNIDADE;

USE MATERNIDADE;

CREATE TABLE MAE(
	COD_MAE INT PRIMARY KEY AUTO_INCREMENT,
    NOME_MAE VARCHAR(100),
    ENDERECO VARCHAR(200),
    TELEFONE_MAE VARCHAR(12),
    DATA_NASC_MAE DATE
);

CREATE TABLE BEBE(
	COD_BEBE INT PRIMARY KEY AUTO_INCREMENT,
    MAE_BEBE INT,
	NOME_BEBE VARCHAR(100),
    DATA_NASC_BEBE DATE,
    PESO DECIMAL(3, 1),
    ALTURA DECIMAL(3, 2),
    -- CHAVES PRIMARIAS --
    FOREIGN KEY (MAE_BEBE) REFERENCES MAE(COD_MAE)
);

CREATE TABLE MEDICO(
	CRM INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    TELEFONE_MEDICO VARCHAR(100),
    ESPECIALIDADE VARCHAR(50)
);

-- MEDICO N:N BEBE EXIGE UMA TABELA INTERMEDIÁRIA --

CREATE TABLE BEBE_MED(
	COD_BEBE INT,
    CRM INT,
	-- CHAVES ESTRANGEIRAS --
    FOREIGN KEY (COD_BEB) REFERENCES BEBE(COD_BEBE),
    FOREIGN KEY (CRM) REFERENCES MEDICO(CRM)
);


